config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/books",to:"books#index"
  post "/books", to:"books#create"
  get "/books/new", to:"books#new", as:"new_book"
  get "/books/:id/edit", to:"books#edit", as:"edit_book"
  get "/books/:id", to:"books#show", as:"book"
  patch "/books/:id", to: "books#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    validates :year, presence: true
    validates :month, presence: true
    validates :inout, presence: true
    validates :category, presence: true
    validates :amount, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
    end

    def show
        @book = Book.find(params[:id])
    end

    def new
        @book = Book.new
    end

    def create
        book_params = params.require(:book).permit(:year,:month,:inout,:category,:amount)
        @book = Book.new(book_params)
        if @book.save
            redirect_to books_path
        else
            render :new
        end
    end

    def update
        @book = Book.find(params[:id])
        book_params = params.require(:book).permit(:year, :month, :inout, :category, :amount)
        if @book.update(book_params)
            redirect_to book_path
        else
            render :edit
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<h1>家計簿更新</h1>

<%= form_with model:@book,local:true,method:"patch" do |f| %>
    
    <div class="formgroup">
        <label>年度</label>
        <%= f.number_field :year, class: "formcontrol"%>
    </div>
    
    <div class="formgroup">
        <label>月</label>
        <%= f.number_field :month, class: "formcontrol" %>
    </div>
    
    <div class="formgroup">
        <label>区分</label>
        <%= f.select:inout,[["収入",1],["支出",2]],{},{class:"formcontrol"}%>
    </div>

    <div class="formgroup">
        <label>科目</label>
        <%= f.text_field :category, class: "form-control" %>
    </div>
    
    <div class="formgroup">
        <label>金額</label>
        <%= f.number_field :amount, class: "formcontrol" %>
    </div>
    
    <%= link_to "戻る", books_path, class: "btn btn-secondary" %>
    <%= f.submit "更新", class: "btn btn-primary" %>
<% end %>

app/views/books/index.html.erb
<h1>家計簿</h1>
<%= link_to "+新規", new_book_path, class:"btn btn-success" %>
<table class="table table-striped">
    <tr>
        <th>年月</th>
        <th>区別</th>
        <th>科目</th>
        <th>金額</th>
        <th>リンク</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
        <td><%= book.year %>年<%= book.month %>月</td>
        <td><%= book.inout %></td>
        <td><%= book.category %></td>
        <td><%= book.amount %>万円</td>
        <td>
            <%= link_to "詳細", book_path(book), class:"btn btn-info" %>
            <%= link_to "編集", edit_book_path(book), class: "btn btn-warning" %>
        </td>
    </tr>
    <% end %>
</table>

app/views/books/new.html.erb
<h1>家計簿新規登録</h1>

<%= form_with model: @book, local: true do |f| %>

    <div class="form-group">
        <label>年度</label>
        <%= f.number_field :year, class: "form-control" %>
    </div>

    <div class="form-group">
        <label>月</label>
        <%= f.number_field :month, class: "form-control" %>
    </div>

    <div class="form-group">
        <label>区分</label>
        <%= f.select :inout, [["収入",1],["支出",2]],{},{class: "form-control"} %>
    </div>

    <div class="form-group">
        <label>科目</label>
        <%= f.text_field :category, class: "form-control" %>
    </div>

    <div class="form-group">
        <label>金額</label>
        <%= f.number_field :amount, class: "form-control" %>
    </div>

    <%= link_to "戻る", books_path, class:"btn-secondary" %>
    <%= f.submit "登録", class:"btn btn-primary" %>
<% end %>

app/views/books/show.html.erb
<h1>家計簿詳細</h1>
<table class="table table-striped">
    <tr>
        <th>年月</th>
        <td><%= @book.year %>年<%= @book.month %>月</td>
    </tr>
    <tr>
        <th>区分</th>
        <td><%= @book.inout %><td>
    </tr>
    <tr>
        <th>科目</th>
        <td><%= @book.category %></td>
    </tr>
    <tr>
        <th>金額</th>
        <td><%= @book.amount %>万円</td>
    </tr>
</tabke>
<%= link_to "戻る", books_path, class:"btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </body>
</html>